global using GameUI.Common;
global using GameUI.Core;
global using GameUI.Core.Enums;
global using GameUI.Core.Interfaces;
global using GameUI.Core.Nodes;
global using GameUI.Core.Sprites;
global using GameUI.ViewModels;
global using GameUI.Views;
global using Microsoft.Maui.Graphics.Platform;
global using System.Text.Json;
global using System.Windows.Input;
global using GraphicsColor = Microsoft.Maui.Graphics.Color;
global using GraphicsImage = Microsoft.Maui.Graphics.IImage;
